// Playwright CLI run-code --filename contract: a standalone async function.
async (page) => {
  const origin = "http://127.0.0.1:1436";
  const errors = [];
  const checks = [];
  const check = (condition, name) => { if (!condition) throw new Error(name); checks.push(name); };
  page.on("pageerror", (error) => errors.push(error.message));
  await page.context().route("**/*", (route) => route.request().url().startsWith(`${origin}/`) ? route.continue() : route.abort());
  await page.addInitScript(() => { window.open = () => null; });
  await page.clock.install();
  const fixture = (body) => page.request.post(`${origin}/__preview/state`, { data: body });
  const refresh = async () => {
    await page.locator("#refresh").click();
    await page.locator("#refresh:not([disabled])").waitFor();
  };
  const events = async () => (await (await page.request.get(`${origin}/__preview/state`)).json()).events;
  await fixture({ scenario: "normal", reset_events: true, challenge: true, growth: [0, 0, 0], restart: { available: true, request: null } });
  await page.setViewportSize({ width: 1120, height: 760 });
  await page.goto(origin);
  await page.locator("#items tr.item-row").first().waitFor();
  check(await page.locator(".stage-nav button").count() === 1, "single collection navigation");
  check(await page.locator("#cards > .card").count() === 5, "five overview cells");
  check(await page.locator("#toggleOverview").count() === 0, "no details toggle");
  check(await page.locator(".metric-card .value").allTextContents().then((values) => values.join() === "3200,1260,730"), "unique counts instead of occurrences");
  check(await page.locator("#engineRestartButton").isDisabled(), "restart disabled without authorization");
  check(await page.locator("#authButton").isEnabled(), "challenge auth available independently from running state");
  await page.clock.fastForward(5_000);
  await refresh();
  check((await page.locator(".pending-growth").count()) === 3, "short refresh does not invent minute delta");
  await fixture({ growth: [7, 3, 2] });
  await page.clock.fastForward(61_000);
  await page.locator(".metric-card .growth-line").first().filter({ hasText: "+7" }).waitFor();
  check((await page.locator(".metric-card .growth-line").allTextContents()).join() === "+7,+3,+2", "observed minute deltas");
  await page.locator("#runtimePauseButton").click();
  await page.getByRole("button", { name: "开始采集", exact: true }).waitFor();
  await page.locator("#runtimePauseButton").click();
  await page.getByRole("button", { name: "暂停采集", exact: true }).waitFor();
  const controlEvents = await events();
  check(controlEvents.some((event) => event.path.endsWith("/control/start")), "start uses ordinary collection control");
  check(!controlEvents.some((event) => event.path.endsWith("/auth/complete")), "start never clears authentication");
  await page.locator('[data-stage="details"]').click();
  await page.locator("#items tr.item-row").first().filter({ hasText: "详情已采集" }).waitFor();
  await page.locator('[data-stage="analysis"]').click();
  await page.locator("#items tr.item-row").first().filter({ hasText: "AI 已分析" }).waitFor();
  check(await page.locator("button[data-stage].active").count() === 1, "stage selection is exclusive");
  await page.locator("#openSettings").click();
  await page.locator("#restartToken").fill("offline-fixture-operator-token-00001");
  await page.locator("#openCollection").click();
  check(await page.locator('[data-stage="analysis"]').getAttribute("aria-pressed") === "true", "settings preserves stage selection");
  await page.locator("#engineRestartButton").click();
  await page.locator('#engineRestartDialog button[value="cancel"]').click();
  check(!(await events()).some((event) => event.path.endsWith("/control/restart")), "cancel never submits restart");
  await page.locator("#engineRestartButton").click();
  await page.locator('#engineRestartDialog button[value="confirm"]').click();
  await page.locator(".restart-status").filter({ hasText: "等待 PC2 接收" }).waitFor();
  check((await events()).filter((event) => event.path.endsWith("/control/restart")).length === 1, "one confirmed restart request");
  check(await page.locator("#engineRestartButton").isDisabled(), "pending restart cannot be double submitted");
  await fixture({ restart: { available: true, request: { status: "succeeded" } } });
  await refresh();
  check((await page.locator(".restart-status").textContent()).includes("Worker 已重启"), "success only comes from controller receipt");
  await page.locator("#authButton").click();
  await page.locator("#authChallengeDialog[open]").waitFor();
  await page.keyboard.press("Escape");
  check((await events()).filter((event) => event.path.endsWith("/control/pause")).length === 1, "opening auth dialog does not add an operator pause");
  await fixture({ challenge: false });
  await refresh();
  check(await page.locator("#authButton").isEnabled(), "no challenge still allows manual authentication");
  await page.locator("#authButton").click();
  await page.locator("#authChallengeDialog[open]").waitFor();
  await page.keyboard.press("Escape");
  check((await events()).filter((event) => event.path.endsWith("/control/pause")).length === 1, "proactive auth entry does not pause collection");
  await fixture({ challenge: true, restart: { available: true, request: null } });
  await refresh();
  await page.locator('[data-stage="links"]').click();
  await page.locator("#toggleRegions").click();
  await page.screenshot({ path: "output/playwright/crow-collection-controls/collection.png", fullPage: true });
  for (const width of [980, 720]) {
    await page.setViewportSize({ width, height: 760 });
    const fits = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth && document.querySelector("main").scrollWidth <= document.querySelector("main").clientWidth);
    check(fits, `no horizontal page overflow at ${width}`);
  }
  await page.screenshot({ path: "output/playwright/crow-collection-controls/narrow.png", fullPage: true });
  await page.setViewportSize({ width: 1120, height: 760 });
  await page.locator("#openSettings").click();
  await page.screenshot({ path: "output/playwright/crow-collection-controls/settings.png", fullPage: true });
  await page.locator("#openCollection").click();
  await fixture({ scenario: "error" });
  await refresh();
  check(await page.locator("#overviewNotice").isVisible(), "connection errors are visible");
  await page.screenshot({ path: "output/playwright/crow-collection-controls/error.png", fullPage: true });
  await fixture({ scenario: "normal" });
  check(errors.length === 0, `no browser exceptions: ${errors.join("; ")}`);
  return { checks, browserErrors: errors };
}
