"""Full migration history and metadata drift, using only isolated databases."""
import os
from pathlib import Path
from uuid import uuid4

from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected
import pytest
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

from src.storage.repository import DatabaseSettings, create_repository_from_env

ROOT = Path(__file__).resolve().parents[2]


def test_repository_requires_explicit_schema_creation(tmp_path, monkeypatch):
    url = "sqlite:///" + (tmp_path / "empty.sqlite3").as_posix()
    monkeypatch.setenv("FAPAI_DB_URL", url)
    monkeypatch.setenv("FAPAI_DB_ENABLED", "1")
    monkeypatch.delenv("FAPAI_DB_AUTO_CREATE", raising=False)
    repo = create_repository_from_env()
    assert repo.settings.auto_create is False
    assert DatabaseSettings(url=url).auto_create is False
    repo.initialize()
    assert inspect(repo.engine).get_table_names() == []
    repo.engine.dispose()
    monkeypatch.setenv("FAPAI_DB_AUTO_CREATE", "1")
    repo = create_repository_from_env()
    repo.initialize()
    assert "fapai_seed_item" in inspect(repo.engine).get_table_names()
    repo.engine.dispose()


@pytest.mark.parametrize("backend", ["sqlite", "postgres"])
def test_full_upgrade_preserves_evidence_and_matches_metadata(tmp_path, monkeypatch, backend):
    if backend == "postgres":
        value = os.environ.get("CROW_TEST_POSTGRES_URL")
        if not value:
            pytest.skip("Dedicated PostgreSQL gate not configured")
        url = make_url(value)
        if url.host not in {"127.0.0.1", "localhost"} or url.database != "crow_quality":
            pytest.fail("Migration tests require loopback crow_quality")
        schema = "schema_gate_" + uuid4().hex
        admin = create_engine(url)
        with admin.begin() as connection:
            connection.exec_driver_sql(f'CREATE SCHEMA "{schema}"')
        admin.dispose()
        engine = create_engine(url.update_query_dict({"options": f"-csearch_path={schema},public"}))
    else:
        engine = create_engine("sqlite:///" + (tmp_path / "migrations.sqlite3").as_posix())
    monkeypatch.delenv("FAPAI_DB_URL", raising=False)
    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(ROOT / "alembic"))
    with engine.begin() as connection:
        config.attributes["connection"] = connection
        # Build the complete schema before exercising the current head. The
        # pre-index revision is the last historical migration that predates
        # this gate's evidence-preservation probe.
        command.upgrade(config, "20260905_0011")
        evidence = '{"_raw_detail_artifacts":{"detail_html_path":"retained.html"},"id":"legacy"}'
        connection.execute(text("INSERT INTO fapai_seed_item (item_id, status, source_payload, detail_attempt_count) "
                                "VALUES ('legacy', 'raw_detail_captured', :payload, 0)"), {"payload": evidence})
        before = connection.execute(text("SELECT source_payload FROM fapai_seed_item WHERE item_id='legacy'")).scalar_one()
        command.upgrade(config, "head")
        after = connection.execute(text("SELECT source_payload FROM fapai_seed_item WHERE item_id='legacy'")).scalar_one()
        assert after == before
        command.check(config)
        # Prove the extension filter cannot turn the drift gate into a no-op.
        # Retain this additive probe in the isolated test database.
        connection.execute(text("ALTER TABLE fapai_seed_item ADD COLUMN quality_drift_probe TEXT"))
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(config)
        assert connection.execute(text("SELECT source_payload FROM fapai_seed_item WHERE item_id='legacy'")).scalar_one() == before
    engine.dispose()
