"""Generate the checked-in desktop contract from the pure Python code registry."""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src import auth_recovery_codes as codes

OUTPUT = ROOT / "collector-desktop" / "src" / "auth_recovery_codes.generated.ts"


def render_contract() -> str:
    exports = {
        "AUTH_ACTIVE_CODES": dict(codes.ACTIVE_CODES),
        "AUTH_FAILURE_CODES": dict(codes.FAILURE_CODES),
        "AUTH_MESSAGES": dict(codes.MESSAGES),
        "AUTH_PHASE_MESSAGES": dict(codes.PHASE_MESSAGES),
    }
    sections = [
        "// Generated by scripts/generate_auth_recovery_codes.py. Do not edit.",
        "// Source: src/auth_recovery_codes.py; no credentials or runtime data.",
    ]
    for name, value in exports.items():
        raw = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)
        sections.append(f"export const {name} = Object.freeze({raw} as const);")
    sections.append(
        f"export const AUTH_TERMINAL_CODE = {json.dumps(codes.TERMINAL_CODE)};"
    )
    sections.append(
        f"export const AUTH_STAGE_VERIFY_CODE = {json.dumps(codes.STAGE_VERIFY_CODE)};"
    )
    return "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail on drift without writing files"
    )
    args = parser.parse_args()
    expected = render_contract()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(
                "Auth recovery contract is stale; run scripts/generate_auth_recovery_codes.py"
            )
            return 1
        print("Auth recovery contract matches Python registry")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
