"""Explicit small offline suites; do not classify every legacy test as quick."""

UNIT_FILES = (
    "test_collection_processing_state.py",
    "test_collection_http_server_concurrency.py",
    "test_collection_jobs.py",
    "test_server_solver_run_ownership.py",
    "test_server_source_contract.py",
    "test_collection_diagnostic_clients.py",
    "test_collection_node_credentials.py",
    "test_collection_api_credentials.py",
    "test_hybrid_seed_collector.py",
    "test_auth_recovery_code_generation.py",
    "test_captcha_dom_evaluation.py",
    "test_captcha_pointer_backend.py",
    "test_desktop_settings_bundle.py",
    "test_runtime_snapshot_cache.py",
    "test_runtime_json.py",
    "test_runtime_state.py",
    "test_runtime_lifecycle.py",
    "test_repository_initialization.py",
    "test_repository_utc_clock.py",
    "test_utc_datetime_type.py",
    "test_server_handler_ingest_utc.py",
    "test_hybrid_timestamp_utc.py",
    "test_status_snapshot_readers.py",
    "test_detail_dispatch_retention.py",
    "test_detail_dispatch_concurrency.py",
    "test_quality_llm_retry.py",
    "test_llm_evidence_boundary.py",
    "test_llm_lazy_config.py",
    "test_llm_selector_waits.py",
    "test_llm_qualification_runtime.py",
    "test_job_progress_durability.py",
    "test_os_pointer_opt_in.py",
    "test_captcha_deadline.py",
    "test_desktop_restart_transport.py",
    "test_seed_maintenance_windows.py",
    "test_watchdog_state_preservation.py",
)
SECURITY_FILES = (
    "test_collection_job_http.py",
    "test_manual_review_job_http.py",
    "test_manual_review_job_view.py",
    "test_report_job_http.py",
    "test_pc1_watcher_transport.py",
    "test_recovery_client_transport.py",
    "test_pc1_python_resolution.py",
    "test_desktop_api_configuration.py",
    "test_maintenance_write_boundary.py",
    "test_item_resource_errors.py",
    "test_collection_node_credentials.py",
    "test_http_write_access.py",
    "test_collection_api_credentials.py",
    "test_archive_json_preservation.py",
    "test_quality_http_guards.py",
    "test_quality_data_preservation.py",
    "test_quality_launcher_security.py",
    "test_http_route_boundaries.py",
    "test_runtime_control_transport.py",
    "test_internal_api_http.py",
    "test_process_supervisor.py",
    "test_collection_api_tls.py",
    "test_avm_evaluate_jobs.py",
    "test_avm_screen_jobs.py",
    "test_detail_location_jobs.py",
    "test_nas_centralization_config.py",
    "test_utc_datetime_migration.py",
)
SUITES = {
    "fast": UNIT_FILES + ("test_quality_http_guards.py",),
    "unit": UNIT_FILES,
    "security": SECURITY_FILES,
    "postgres": (
        "test_quality_postgres_claims.py",
        "test_collection_query_indexes.py",
        "test_schema_migration_gate.py",
        "test_seed_candidate_windows.py",
        "test_search_claim_streaming.py",
        "test_utc_datetime_migration.py",
    ),
}
