// Generated by scripts/generate_auth_recovery_codes.py. Do not edit.

// Source: src/auth_recovery_codes.py; no credentials or runtime data.

export const AUTH_ACTIVE_CODES = Object.freeze({
  "pc1_claimed": "existing_recovery",
  "pc2_claimed": "pc2_importing",
  "requested": "existing_recovery",
  "restarting": "pc2_restarting",
  "snapshot_ready": "pc2_receiving",
  "verifying": "pc2_verifying"
} as const);

export const AUTH_FAILURE_CODES = Object.freeze({
  "challenge_changed": "challenge_changed",
  "desktop_manual_takeover": "desktop_manual_takeover",
  "operator_pause_active": "operator_pause_active",
  "pc1_claimed_timeout": "pc1_publish_timeout",
  "pc2_claimed_timeout": "pc2_import_timeout",
  "requested_timeout": "pc1_receive_timeout",
  "restarting_timeout": "pc2_restart_timeout",
  "snapshot_ready_timeout": "pc2_receive_timeout",
  "stage_probe_failed": "stage_probe_failed",
  "stage_probe_unavailable": "stage_probe_unavailable",
  "verifying_timeout": "pc2_progress_timeout"
} as const);

export const AUTH_MESSAGES = Object.freeze({
  "api_not_configured": "当前 API 与本机认证配置不同，未发送认证凭据。",
  "api_upgrade_required": "NAS 尚未安装认证同步接口。",
  "browser_unavailable": "挑战浏览器未能打开，请检查本机认证组件。",
  "challenge_changed": "当前采集页面或挑战已变化，请重新打开实际采集页面后提交；默认列表页的认证不能确认地区列表恢复。",
  "challenge_page_not_ready": "请先在打开的挑战页面完成认证，再点击已完成挑战。",
  "desktop_manual_takeover": "本次恢复已由桌面人工认证接管，请查看当前认证任务。",
  "existing_recovery": "已有认证恢复任务正在处理，等待 PC1 交接和 PC2 验证。",
  "handoff_busy": "另一认证交接正在进行，请稍后重试。",
  "invalid_snapshot": "认证快照格式无效，原有会话未被覆盖。",
  "operator_pause_active": "采集已被手动暂停，认证恢复没有自动解除暂停。",
  "pc1_publish_timeout": "PC1 已领取请求，但未按时发布认证快照，请检查本机认证组件。",
  "pc1_receive_timeout": "PC1 未在规定时间内领取认证请求，请检查本机认证组件。",
  "pc2_import_timeout": "PC2 已领取快照，但导入会话超时，请检查 PC2 认证组件。",
  "pc2_importing": "PC2 已领取认证快照，正在导入会话。",
  "pc2_progress_timeout": "PC2 已接收会话，但尚未观察到采集恢复；认证恢复验证已超时。",
  "pc2_receive_timeout": "PC2 未在规定时间内领取认证快照，请检查 PC2 认证组件。",
  "pc2_receiving": "认证快照已提交，等待 PC2 领取。",
  "pc2_restart_timeout": "PC2 已导入会话，但认证浏览器重启超时。",
  "pc2_restarting": "PC2 已导入认证会话，正在重启认证浏览器。",
  "pc2_stage_upgrade_required": "PC2 分阶段认证组件尚未就绪；未发送 Cookie，请先更新或检查 PC2 认证组件。",
  "pc2_stage_verifying": "PC2 已导入认证会话，正在验证此阶段的真实页面，无需重启浏览器。",
  "pc2_verifying": "PC2 已接收会话，正在确认采集恢复。",
  "recovery_unknown": "NAS 未返回本次恢复记录，暂时无法确认结果；请刷新状态。",
  "runtime_config_invalid": "本机认证配置无法读取，请修复桌面安装目录中的运行配置。",
  "session_not_reusable": "浏览器会话尚未通过复用验证，请完成挑战后重试；PC2 保持等待。",
  "shared_partial": "同一份 Cookie 的两个阶段处理已结束，但未全部确认恢复；请查看各阶段状态。",
  "shared_queued": "已保存本次认证 Cookie，等待当前交接结束后自动同步两个阶段，无需重复点击。",
  "shared_receiving": "同一份 Cookie 正在依次同步给链接采集和详情采集，无需再次人工认证。",
  "shared_retry": "认证 Cookie 已保存，交接连接暂时不可用，正在自动重试，无需再次认证。",
  "shared_snapshot_expired": "等待交接超过 30 分钟，未继续使用旧 Cookie，请重新提交当前浏览器会话。",
  "shared_succeeded": "同一份 Cookie 已用于链接和详情采集，两个阶段均已确认恢复。",
  "stage_api_upgrade_required": "NAS 尚未升级分阶段认证接口；未发送 Cookie，请先更新 NAS 认证组件。",
  "stage_probe_failed": "PC2 的链接页面仍未通过有效数据验证，请重新打开此阶段的挑战页面。",
  "stage_probe_unavailable": "认证快照已到达 PC2，但浏览器或网络探测不可用；这不是人工挑战失败，请检查 PC2 后重新提交。",
  "token_rejected": "认证同步凭据未被 NAS 接受。",
  "token_unavailable": "本机缺少认证同步凭据，请检查认证组件配置。"
} as const);

export const AUTH_PHASE_MESSAGES = Object.freeze({
  "failed": "PC2 未能确认恢复，请重新打开挑战页面后重试。",
  "pending_human": "认证会话尚未就绪，请完成挑战后重试。",
  "pending_pc2": "认证快照已提交，等待 PC2 接收和验证。",
  "ready_for_human": "挑战页面已打开。",
  "succeeded": "此阶段认证已确认；其他阶段的认证状态独立显示。",
  "unavailable": "认证同步暂不可用，请稍后重试。"
} as const);

export const AUTH_TERMINAL_CODE = "recovery_finished";

export const AUTH_STAGE_VERIFY_CODE = "pc2_stage_verifying";
